### ISSUE TITLE
运行不起来，请看一下什么问题

### ISSUE THREAD

**Issue by guoguogis** [Frey-Fu/ng2-echarts#1]
运行 `typings install`就开始报错了：

C:\Users\Administrator\Desktop\ng2-echarts-master\example>typings install
typings ERR! message EEXIST: file already exists, mkdir 'C:\Users\Administrator\
Desktop\ng2-echarts-master\example\typings'
typings ERR!
typings ERR! cwd C:\Users\Administrator\Desktop\ng2-echarts-master\example
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administr
ator\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v4.4.4
typings ERR! typings -v 2.1.0
typings ERR! code EEXIST
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

**Comment by Frey-Fu** [comment]
看起来是typings已有且不能覆盖，你试试跳过这条命令，直接跑后面的npm run build看看。

**Comment by guoguogis** [comment]
也不行，难道nodejs版本不对？
 94% asset optimizationError in bail mode: [default] D:\work\isource\Frey-Fu\ng2
-echarts-master\example\node_modules\@types\jasmine\index.d.ts:39:37
A parameter initializer is only allowed in a function or constructor implementat
ion.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build:prod"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.5 build:prod: `webpack --config config/web
pack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.0.5 build:prod script 'webpack
 --config config/webpack.prod.js  --progress --profile --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-star
ter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config config/webpack.prod.js  --progress --profile --bai
l
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\work\isource\Frey-Fu\ng2-echarts-master\example\npm-debug.log

**Comment by Frey-Fu** [comment]
看起来npm包依赖的地方出错了，https://github.com/angular/material2/issues/3074这里有提到，
新版本的jasmin引入了bug，说是把jasmin的版本降低一下就可以了：
Solved this by reducing the @types/jasmine to 2.5.38
你试试这样行不行，实在不行的话，我把我这边的npm包打包发给你，qq邮箱或者是什么别的。

**Comment by guoguogis** [comment]
还是有问题，请发我一下，谢谢。
627668470@qq.com

**Comment by Frey-Fu** [comment]
已发送，请查收。
